---
title: 'Oregon Extended Analyses: 2019'
author: 
- "Brock Rowley"
- "Sevrina Tindal"
- "Philip Irvin"
- "Daniel Anderson"
- "Gerald Tindal"
affiliation: "University of Oregon"
date: "6/29/2019"
output: 
  pdf_document:
    toc: yes
    toc_depth: 5
    keep_tex: yes
  #   toc: true
  #   toc_float: true
  #   toc_depth: 4
  # html_document:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '4'
header-includes:
  - \pagenumbering{gobble}
  - \usepackage{placeins}
  - \usepackage{float}
  - \usepackage{caption}
  - \captionsetup[figure]{labelformat = empty}
  - \usepackage{xcolor}
  - \definecolor{link}{rgb}{0, 0, 238}
  - \usepackage{booktabs}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```
## Appendix Descriptions
<!-- "/System/Library/Automator/Combine PDF Pages.action/Contents/Resources/join.py" -o merged.pdf Figures/TechReport_Appendices/*.pdf -->

#### Appendix 1.1 

*Appendix* 1.1 explains the development process and intended uses for the
Essentialized Assessment Frameworks (EAFs). The EAFs are the essentialized
standards (EsSt), which are linked to grade level content standards. The ORExt
is aligned to the EAFs, as well. While the EAFs primarily guide item
development, they are also intended to be used in the development of appropriate
Present Levels of Functional and Academic Performance (PLAAFP) statements and
Individualized Education Program (IEP) goals and objectives.
\newpage

#### Appendix 1.2 

*Appendix* 1.2 conveys the evaluation conducted by researchers at the Fordham
Institute, which compared then-current state standards to the CCSS in terms of
rigor. The findings generally show that the CCSS are as rigorous or more
rigorous than state standards.

#### Appendix 1.4.1 

*Appendix* 1.4.1 is the Executive Memo from the Governor of Oregon regarding
parent opt-out expectations. 

#### Appendix 1.4.2 

*Appendix* 1.4.2 is the test
administration manual (TAM) for all assessments in the Oregon statewide
assessment system, including the SBA, OAKS, the ORExt, the Kindergarten
Assessment, and the ELPA. The TAM elaborates all relevant test security and
administration procedures. 

#### Appendix 1.4A.1 

*Appendix* 1.4A.1 is ODE's English
Learner Program Guide, outlining English learner (EL) system requirements in the
areas of student identification, services, reporting, and assessment for ELs in
Oregon's public schools, including ELs who are SWD.

#### Appendix 1.4A.2 

*Appendix* 1.4A.2 is Oregon's regulations that require ODE to provide translated
OAKS assessments for populations at or above 9% in grades K-12 within three
years after the school year in which the language exceeds the threshold.

#### Appendix 1.5

*Appendix* 1.5 is Oregon's annual report to the state legislature for the
2015-16 school year. The report includes student demographics and information on
student groups, school funding and staff information, test results, graduation
and drop out rates, charter school data and information on alternative education
programs, early childhood data, and attendance and chronic absenteeism data.

#### Appendix 2.1

*Appendix* 2.1 is the test specifications document that describes our approach
to assessment and test design for the ORExt. The document includes our approach
to RDBC, an overview of the essentialization process and EAF documents, the
anticipated operational test design for the ORExt, test development
considerations, sample test items, item specifications, and universal
tools/designated supports/accommodations.

#### Appendix 2.1A 

*Appendix* 2.1A provides the field with comprehensive information related to
scaled score interpretation for the ORExt. The guidance is published in three
main areas: 1) Annual performance, 2) Annual growth, and 3) Performance for very
low functioning students. Guidance regarding use and interpretation of reading
and writing subscores is also provided. 

#### Appendix 2.1B 

*Appendix* 2.1B is the
test blueprint for the ORExt, conveying the balance of representation of domains
across the content areas and grade levels assessed. Operational items are
selected to reflect the representation percentages included in the test
blueprint.

#### Appendix 2.1C 

*Appendix* 2.1C describes the eight-step item development process used to
develop items for the ORExt, from standard selection to test booklet formation.
The item development process is specific and explicit in order to increase
transparency.

#### Appendix 2.2.1 

*Appendix* 2.2.1 is the set of PPT slides that were used to train item writers
for the ORExt. Item writers were also provided an orientation to the test
specifications as part of training.

#### Appendix 2.2.2 

*Appendix* 2.2.2 is a document that summarizes the balanced design vertical
scaling plan employed for the ORExt in the 2014-15 administration. The document
includes the domain sampling plan for all assessments, as well as the decision
rules employed to remove items from the operational item pool prior to vertical
scaling and standard setting procedures.

#### Appendix 2.2.3 

*Appendix* 2.2.3 provides stakeholders with visual representation of the
structure of the ORExt. Sample items are conveyed in English language arts,
mathematics, and science, with the scoring protocol and student materials
presented together. Stakeholders can see the structure of each item, as well as
how the items are scored. They can also gather an idea about the types of
formats that are used for answer choices that are included within the student
materials documents.

#### Appendix 2.3 

*Appendix* 2.3 is ODE's General Administration and Scoring Manual for 2017-18.
The manual establishes ODE's expectations regarding the test window, utilizing
the ORExt training and proficiency website, using the sign language interpreter
training and proficiency website, and informing parents. It also provides the
following information for stakeholders, including educators and parents:
Overview of the Extended Assessments,	Assessing a Student, Scoring, Decision
Making, and	Information for Teachers. The manual provides three appendices that
provide guidance regarding the provision of supports, parent questions and
answers, and a glossary.

#### Appendix 2.3A.1 

*Appendix* 2.3A.1 is the 2017-18 accessibility options manual for all
assessments in the Oregon statewide assessment system, including the SBA, OAKS,
the ORExt, and the ELPA. Options include Universal Tools, Designated Supports,
and Accommodations. The manual provides guidance regarding use of these options
in instruction and assessment, as well as implementation strategies and use
evaluation. Each accommodation is coded for use in data analysis related to
assessment scores for the SBA and OAKS.

#### Appendix 2.3A.2 

*Appendix* 2.3A.2 is ODE's How to Select, Administer, and Evaluate
Accommodations on Oregon's Statewide Assessment manual for 2013-14. The manual
trains users regarding how to implement and evaluate appropriate accommodations,
from the student level to the systems level.

#### Appendix 2.3A.3 

*Appendix* 2.3A.3 is a document that summarizes the procedures used during item
development to reduce item depth, breadth, and complexity, in addition to the
test specifications information found in *Appendix* 2.1. The document also
provides more detail regarding how language complexity is addressed and reviewed
in an effort to decrease the language load of items and make the test more
accessible to all students. The document also discusses ways in which bias is
addressed during test development.

#### Appendices 2.3B.1-2.3B.2 

Appendices 2.3B.1 and 2.3B.2 are the PowerPoint (PPT) trainings that were used
by ODE and BRT trainers to train new qualified assessors (QAs) and qualified
trainers (QTs) in four regionally hosted trainings in November 2017. QTs also
used the package to train New Qualified Assessors for the 2017-18 school year.
The training provides participants with the information needed to pass
proficiency tests as part of the requirements to become a QA for the Oregon
Extended Assessments and was delivered by QTs throughout the state. The training
package addresses the following topics: "What's new in 2017-18?",	"2018 Test
Window", "Eligibility - which students take AA-AAAS?", "Test administration",
"Student Confidentiality & Test Security", "Test Administration (Physical &
Logistic)",	"Scoring & Data Entry",	"Reports & Sharing Results with Parents",
"Navigating the Training and Proficiency website", and "Resources."

#### Appendix 2.3B.4 

*Appendix* 2.3B.4 is the test calendar for the entire Oregon statewide
assessment program, including the SBA, OAKS, the ORExt, the ELPA, the
Kindergarten Assessment, and the NAEP.

#### Appendix 2.3B.5 

*Appendix* 2.3B.5 is a sample agenda that ODE makes available to QTs around the
state to train their respective new QAs as they implement the train-the-trainers
model used by the Oregon Extended assessment.

#### Appendix 2.3B.6 

*Appendix* 2.3B.6 is the list of instructions provided to new QAs and QTs
regarding how to access the online training and proficiency website.

#### Appendix 2.3B.7 

*Appendix* 2.3B.7 is the list of responsibilities associated with being a QT for
the ORExt assessment.

#### Appendix 2.3B.8 

*Appendix* 2.3B.8 is the document that contains the most commonly fielded
questions and answers from stakeholders, including parents and teachers.

#### Appendix 2.3B.9 

*Appendix* 2.3B.9 is the Helpdesk log report that summarizes all of the
technical assistance questions garnered from the field this year. Efforts are
made to find any patterns that our team may use to improve training for the
following year.

#### Appendix 2.3B.10 

*Appendix* 2.3B.10 is the consequential validity report for the spring 2017
consequential validity study conducted by BRT. The report provides documentation
of the perceptions in the field related to both intended and unintended academic
and social consequences of the ORExt. 

#### Appendices 2.6 

*Appendix* 2.6 is the data entry guide. The guide explains the paper/pencil data
entry process located on ODE's secure server.

#### Appendices 2.6A

*Appendix* 2.6A is the ORExt Test Application User Guide. With 2017-18 the first
year the tablet/web-based platform was available for all grade level and subject
area tests, this guide walked through the system requirements, download/login
instructions, testing process, and troubleshooting.

#### Appendix 2.6C 

*Appendix* 2.6C is the manual defining the state of Oregon's policies and
procedures regarding how students are included in AMO reporting, including how
achievement, growth, and graduation rates are reported for student groups and
subgroups.

#### Appendix 3.1A

*Appendix* 3.1A is a document that summarizes the independent alignment study
process and participants used to review the linkage between the Essentialized
Standards and grade level content standards (CCSS in ELA and Math; ORSci and
NGSS in Science), as well as the alignment between test items for the ORExt with
those Essentialized Standards. In addition, reviewers rated the items for
potential bias and access concerns. All data was gathered using the Distributed
Item Review (DIR) website, supported by a webinar training and ongoing technical
assistance. The results of the 2014-15 Linkage Study, which was not independent
but run by BRT researchers, are also included.

#### Appendix 3.1B 

*Appendix* 3.1B is a document that describes the Distributed Item Review (DIR)
website used by Oregon teachers to evaluate the alignment between test items for
the ORExt with Essentialized Standards. In addition, reviewers rated the items
for potential bias and access concerns. All data was gathered using the DIR
website, supported by a webinar training and ongoing technical assistance.

#### Appendices 4.1

*Appendix* 4.1 is the Inter-rater Reliability Study Observation form completed
by study participants.

#### Appendix 4.1B 

*Appendix* 4.1B conveys the historical development of the ORExt from 1999 to the
present, including the grade levels/bands assessed, content areas assessed, and
the targeted content standards.

#### Appendix 4.2 

*Appendix* 4.2 includes the most current published state level data regarding
Oregon's ethnic diversity.

#### Appendix 5.1B 

*Appendix* 5.1B is the revised and rigorous guidance that ODE has provided to
IEP teams to assist them in making appropriate assessment eligibility
determinations for students with disabilities.

#### Appendix 5.1D 

*Appendix* 5.1D includes a
summary report of the statewide results and the administration and scoring
instructions for the new Oregon Observational Rating Assessment (ORora). The
ORora is administered to all students whose ORExt testing was discontinued. It
provides information regarding student progress in terms of functional skills in
adaptive and communication domains for the small subgroup of students who are
unable to meet the academic expectations in the ORExt.

#### Appendix 6.1A.1 

*Appendix* 6.1A.1 is the agenda and minutes that document the hearing and
adoption of the AAAS for the ORExt on June 25, 2015.

#### Appendix 6.1A.2 

*Appendix* 6.1A.2 includes all of the achievement level descriptors (ALDs) and
cutscores that define performance for the ORExt in qualitative and quantitative
fashions, respectively. These Alternate Academic Achievement Standards (AAAS)
describe what students should know and be able to do based upon their
performance on the ORExt.

#### Appendix 6.2.1 

*Appendix* 6.2.1 is the PPT slides used to train standard setters during the
June 2015 standard setting meetings for ELA, math, and science.

#### Appendix 6.2.2 

*Appendix* 6.2.2 is a standard setting report generated by an independent
auditor. The report provides a comprehensive evaluation of the bookmark standard
setting procedure employed for the ORExt on June 15-17, 2015.

#### Appendix 6.4C 

*Appendix* 6.4C is a document that displays the individual student report (ISR)
that ODE publishes for students who participate in the ORExt. The mock-up
includes cut scores and achievement level descriptors (ALDs), as well as links
to the ODE website for additional information.